title: Shikha Mallick
# tagline: Here is personal website of Shikha Mallick. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: Two roads diverged in woods, I took the one less traveled by.
#Comment out url when working locally to resolve base urls correctly
#url: https://caihanlin.com

# Owner/author information
owner:
  name: Shikha Mallick
  avatar: Photo_Shikha_Mallick.jpg
 # bio:
  email: mallickshikha@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: shikha_mallick
  github: mshik
  linkedin: shikha-mallick
  scholar: https://scholar.google.com/citations?user=EbFcbBIAAAAJ&hl=en

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
#google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Resume
    url: /file/CV_Shikha_Mallick.pdf
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Kolkata
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2024/06/24 by Shikha Mallick.
